// <auto-generated />
using System;
using D_S_Grok.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace D.S_Grok.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604094528_SeedLinkedListChallenge")]
    partial class SeedLinkedListChallenge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("D_S_Grok.Models.Achievement", b =>
                {
                    b.Property<int>("AchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AchievementID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RequirementValue")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("XPReward")
                        .HasColumnType("int");

                    b.HasKey("AchievementID");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            AchievementID = 1,
                            Description = "Complete your first lesson.",
                            RequirementType = "CompletedLessons",
                            RequirementValue = 1,
                            Title = "First Steps",
                            XPReward = 25
                        },
                        new
                        {
                            AchievementID = 2,
                            Description = "Complete Level 1.",
                            RequirementType = "CompletedLevel",
                            RequirementValue = 1,
                            Title = "Pointer Explorer",
                            XPReward = 50
                        },
                        new
                        {
                            AchievementID = 3,
                            Description = "Complete Level 2.",
                            RequirementType = "CompletedLevel",
                            RequirementValue = 2,
                            Title = "List Master",
                            XPReward = 50
                        },
                        new
                        {
                            AchievementID = 4,
                            Description = "Complete Level 3.",
                            RequirementType = "CompletedLevel",
                            RequirementValue = 3,
                            Title = "Linked List Expert",
                            XPReward = 100
                        },
                        new
                        {
                            AchievementID = 5,
                            Description = "Achieve 100% on any quiz.",
                            RequirementType = "PerfectQuizScore",
                            RequirementValue = 100,
                            Title = "Quiz Champion",
                            XPReward = 75
                        });
                });

            modelBuilder.Entity("D_S_Grok.Models.Challenge", b =>
                {
                    b.Property<int>("ChallengeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChallengeID"));

                    b.Property<string>("ChallengeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LevelID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("XPReward")
                        .HasColumnType("int");

                    b.HasKey("ChallengeID");

                    b.HasIndex("LevelID");

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            ChallengeID = 1,
                            ChallengeType = "ListTraversal",
                            Description = "Build a linked list visually and observe how nodes are connected through pointers.",
                            LevelID = 2,
                            Title = "Create and Traverse a Linked List",
                            XPReward = 75
                        });
                });

            modelBuilder.Entity("D_S_Grok.Models.ChallengeAttempt", b =>
                {
                    b.Property<int>("ChallengeAttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChallengeAttemptID"));

                    b.Property<int>("AttemptsCount")
                        .HasColumnType("int");

                    b.Property<int>("ChallengeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ChallengeAttemptID");

                    b.HasIndex("ChallengeID");

                    b.HasIndex("UserID", "ChallengeID")
                        .IsUnique();

                    b.ToTable("ChallengeAttempts");
                });

            modelBuilder.Entity("D_S_Grok.Models.Lesson", b =>
                {
                    b.Property<int>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LessonID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LessonOrder")
                        .HasColumnType("int");

                    b.Property<int>("LevelID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("XPReward")
                        .HasColumnType("int");

                    b.HasKey("LessonID");

                    b.HasIndex("LevelID");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            LessonID = 1,
                            Content = "A pointer is a variable that stores the memory address of another variable.",
                            LessonOrder = 1,
                            LevelID = 1,
                            Title = "What is a Pointer?",
                            XPReward = 50
                        },
                        new
                        {
                            LessonID = 2,
                            Content = "Pointers can reference values and be reassigned to point to different memory locations.",
                            LessonOrder = 2,
                            LevelID = 1,
                            Title = "Pointer Assignment and References",
                            XPReward = 50
                        },
                        new
                        {
                            LessonID = 3,
                            Content = "A node is a structure that stores data and a reference to the next node.",
                            LessonOrder = 1,
                            LevelID = 2,
                            Title = "What is a Node?",
                            XPReward = 50
                        },
                        new
                        {
                            LessonID = 4,
                            Content = "A linked list is created by connecting nodes together using pointers.",
                            LessonOrder = 2,
                            LevelID = 2,
                            Title = "Creating a Linked List",
                            XPReward = 50
                        },
                        new
                        {
                            LessonID = 5,
                            Content = "Traversal means moving from one node to the next until the end of the list is reached.",
                            LessonOrder = 3,
                            LevelID = 2,
                            Title = "Traversing a Linked List",
                            XPReward = 50
                        },
                        new
                        {
                            LessonID = 6,
                            Content = "Insertion requires updating pointers so that the new node becomes part of the list.",
                            LessonOrder = 1,
                            LevelID = 3,
                            Title = "Inserting a Node",
                            XPReward = 50
                        },
                        new
                        {
                            LessonID = 7,
                            Content = "Deletion removes a node by updating the previous node pointer to skip the removed node.",
                            LessonOrder = 2,
                            LevelID = 3,
                            Title = "Deleting a Node",
                            XPReward = 50
                        },
                        new
                        {
                            LessonID = 8,
                            Content = "Searching checks each node until the target value is found, then the node data may be updated.",
                            LessonOrder = 3,
                            LevelID = 3,
                            Title = "Searching and Updating Nodes",
                            XPReward = 50
                        });
                });

            modelBuilder.Entity("D_S_Grok.Models.LessonProgress", b =>
                {
                    b.Property<int>("LessonProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LessonProgressID"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LessonProgressID");

                    b.HasIndex("LessonID");

                    b.HasIndex("UserID", "LessonID")
                        .IsUnique();

                    b.ToTable("LessonProgress");
                });

            modelBuilder.Entity("D_S_Grok.Models.Level", b =>
                {
                    b.Property<int>("LevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LevelID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("int");

                    b.Property<int>("RequiredXP")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("LevelID");

                    b.HasIndex("LevelNumber")
                        .IsUnique();

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            LevelID = 1,
                            Description = "Introduction to memory references and pointer concepts.",
                            LevelNumber = 1,
                            RequiredXP = 0,
                            Title = "Pointer Fundamentals"
                        },
                        new
                        {
                            LevelID = 2,
                            Description = "Introduction to nodes, head pointer, and traversal.",
                            LevelNumber = 2,
                            RequiredXP = 150,
                            Title = "Linked Lists"
                        },
                        new
                        {
                            LevelID = 3,
                            Description = "Insertion, deletion, searching, and updating nodes.",
                            LevelNumber = 3,
                            RequiredXP = 350,
                            Title = "Linked List Operations"
                        });
                });

            modelBuilder.Entity("D_S_Grok.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("QuizID");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionID = 1,
                            Explanation = "PTR stores the memory address of X, not the value stored inside X.",
                            QuestionText = "After assigning PTR = &X, what value does PTR store?",
                            QuizID = 1
                        },
                        new
                        {
                            QuestionID = 2,
                            Explanation = "&X represents the memory address of variable X.",
                            QuestionText = "If X has value 10 and address 1001, what does &X represent?",
                            QuizID = 1
                        },
                        new
                        {
                            QuestionID = 3,
                            Explanation = "NULL means the pointer is not currently pointing to any valid memory address.",
                            QuestionText = "What does NULL mean when used as a pointer value?",
                            QuizID = 1
                        });
                });

            modelBuilder.Entity("D_S_Grok.Models.QuestionOption", b =>
                {
                    b.Property<int>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OptionID"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("OptionID");

                    b.HasIndex("QuestionID");

                    b.ToTable("QuestionOptions");

                    b.HasData(
                        new
                        {
                            OptionID = 1,
                            IsCorrect = false,
                            OptionText = "10",
                            QuestionID = 1
                        },
                        new
                        {
                            OptionID = 2,
                            IsCorrect = true,
                            OptionText = "1001",
                            QuestionID = 1
                        },
                        new
                        {
                            OptionID = 3,
                            IsCorrect = false,
                            OptionText = "X",
                            QuestionID = 1
                        },
                        new
                        {
                            OptionID = 4,
                            IsCorrect = false,
                            OptionText = "NULL",
                            QuestionID = 1
                        },
                        new
                        {
                            OptionID = 5,
                            IsCorrect = false,
                            OptionText = "The value of X",
                            QuestionID = 2
                        },
                        new
                        {
                            OptionID = 6,
                            IsCorrect = false,
                            OptionText = "The name of X",
                            QuestionID = 2
                        },
                        new
                        {
                            OptionID = 7,
                            IsCorrect = true,
                            OptionText = "The address of X",
                            QuestionID = 2
                        },
                        new
                        {
                            OptionID = 8,
                            IsCorrect = false,
                            OptionText = "The data type of X",
                            QuestionID = 2
                        },
                        new
                        {
                            OptionID = 9,
                            IsCorrect = true,
                            OptionText = "The pointer has no target address",
                            QuestionID = 3
                        },
                        new
                        {
                            OptionID = 10,
                            IsCorrect = false,
                            OptionText = "The pointer stores zero XP",
                            QuestionID = 3
                        },
                        new
                        {
                            OptionID = 11,
                            IsCorrect = false,
                            OptionText = "The pointer stores the value 10",
                            QuestionID = 3
                        },
                        new
                        {
                            OptionID = 12,
                            IsCorrect = false,
                            OptionText = "The pointer deletes the variable",
                            QuestionID = 3
                        });
                });

            modelBuilder.Entity("D_S_Grok.Models.Quiz", b =>
                {
                    b.Property<int>("QuizID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QuizID"));

                    b.Property<int>("LevelID")
                        .HasColumnType("int");

                    b.Property<int>("PassMark")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("XPReward")
                        .HasColumnType("int");

                    b.HasKey("QuizID");

                    b.HasIndex("LevelID");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            QuizID = 1,
                            LevelID = 1,
                            PassMark = 60,
                            Title = "Pointer Fundamentals Quiz",
                            XPReward = 100
                        });
                });

            modelBuilder.Entity("D_S_Grok.Models.QuizAttempt", b =>
                {
                    b.Property<int>("QuizAttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QuizAttemptID"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.Property<int>("ScorePercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("QuizAttemptID");

                    b.HasIndex("QuizID");

                    b.HasIndex("UserID");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("D_S_Grok.Models.QuizAttemptAnswer", b =>
                {
                    b.Property<int>("QuizAttemptAnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QuizAttemptAnswerID"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("QuizAttemptID")
                        .HasColumnType("int");

                    b.Property<int>("SelectedOptionID")
                        .HasColumnType("int");

                    b.HasKey("QuizAttemptAnswerID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("QuizAttemptID");

                    b.HasIndex("SelectedOptionID");

                    b.ToTable("QuizAttemptAnswers");
                });

            modelBuilder.Entity("D_S_Grok.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalXP")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("D_S_Grok.Models.UserAchievement", b =>
                {
                    b.Property<int>("UserAchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserAchievementID"));

                    b.Property<int>("AchievementID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserAchievementID");

                    b.HasIndex("AchievementID");

                    b.HasIndex("UserID", "AchievementID")
                        .IsUnique();

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("D_S_Grok.Models.XPTransaction", b =>
                {
                    b.Property<int>("XPTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("XPTransactionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SourceReferenceID")
                        .HasColumnType("int");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("XPAmount")
                        .HasColumnType("int");

                    b.HasKey("XPTransactionID");

                    b.HasIndex("UserID");

                    b.ToTable("XPTransactions");
                });

            modelBuilder.Entity("D_S_Grok.Models.Challenge", b =>
                {
                    b.HasOne("D_S_Grok.Models.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("D_S_Grok.Models.ChallengeAttempt", b =>
                {
                    b.HasOne("D_S_Grok.Models.Challenge", "Challenge")
                        .WithMany()
                        .HasForeignKey("ChallengeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D_S_Grok.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("D_S_Grok.Models.Lesson", b =>
                {
                    b.HasOne("D_S_Grok.Models.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("D_S_Grok.Models.LessonProgress", b =>
                {
                    b.HasOne("D_S_Grok.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D_S_Grok.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("D_S_Grok.Models.Question", b =>
                {
                    b.HasOne("D_S_Grok.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("D_S_Grok.Models.QuestionOption", b =>
                {
                    b.HasOne("D_S_Grok.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("D_S_Grok.Models.Quiz", b =>
                {
                    b.HasOne("D_S_Grok.Models.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("D_S_Grok.Models.QuizAttempt", b =>
                {
                    b.HasOne("D_S_Grok.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D_S_Grok.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("D_S_Grok.Models.QuizAttemptAnswer", b =>
                {
                    b.HasOne("D_S_Grok.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D_S_Grok.Models.QuizAttempt", "QuizAttempt")
                        .WithMany()
                        .HasForeignKey("QuizAttemptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D_S_Grok.Models.QuestionOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("QuizAttempt");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("D_S_Grok.Models.UserAchievement", b =>
                {
                    b.HasOne("D_S_Grok.Models.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D_S_Grok.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("D_S_Grok.Models.XPTransaction", b =>
                {
                    b.HasOne("D_S_Grok.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
